### ISSUE TITLE
Auto complete is broken after upgrading to 1.17 

### ISSUE THREAD

**Issue by mohamed-samir-mohamed** [Pure-D/code-d#173]
it is totally broken, it was working very well in the old version 1.16.3 now I cannot even find the dcd server and the path for it is missing.

**Comment by mohamed-samir-mohamed** [comment]
linux Ubuntu 16.04.4 LTS

I was using the d.projectImportPaths setting to point out the files I want to load

**Comment by mohamed-samir-mohamed** [comment]
upon opening any D file I get this message in the termainal  and stuck there...

Installing into /home/muhammad/.local/share/code-d/bin

**Comment by WebFreak001** [comment]
can you check if the developer tools contain any error? If it's stuck there it won't start serve-d.

`ctrl-shift-p -> toggle developer tools` in the console tab

**Comment by WebFreak001** [comment]
ok seems like it has problems attempting to remove old serve-d folder (because new version is released and you probably have the betaStream setting, so you will automatically get it)

**Comment by WebFreak001** [comment]
can you manually remove serve-d from that path? It seems like it is a directory even though it should be an executable file

**Comment by WebFreak001** [comment]
hm or actually no, it is always a directory, not sure why it complains there...

**Comment by mohamed-samir-mohamed** [comment]
so remove or not ?

**Comment by WebFreak001** [comment]
yes try removing it, remove the entire ~/.local/share/code-d folder to be sure.

**Comment by mohamed-samir-mohamed** [comment]
yeah it passed this step, but now I have these errors
![image](https://user-images.githubusercontent.com/1665565/38558860-c5d38d0e-3cd1-11e8-9e3c-dde3aff718fe.png)

**Comment by WebFreak001** [comment]
can you do one quick test, does it work (after serve-d has already been loaded and stdlib completes correctly) if you add and remove a dummy folder to the `d.projectImportPaths` setting

**Comment by mohamed-samir-mohamed** [comment]
ok I actually tried to remove all my import paths and still in the output tries to load every thing,

 "window.zoomLevel": 0,
    "editor.fontSize": 12,
    "editor.renderWhitespace": "all",
    "d.neverUseDub": true,
    "debug.allowBreakpointsEverywhere": true,
    "d.enableDubLinting": false,
    "dfmt.braceStyle": "stroustrup",
    "d.enableLinting": false,
    "d.overrideDfmtEditorconfig": false,
    "d.stdlibPath": [
        "/usr/include/dmd/phobos",
        "/usr/include/dmd/druntime/import"
    ],
    "d.projectImportPaths": [
    ],
    "gitlens.keymap": "none",
    "workbench.colorTheme": "Default Dark+",
    "d.servedPath": "/home/muhammad/.local/share/code-d/bin/serve-d",
    "d.dcdClientPath": "/home/muhammad/.local/share/code-d/bin/DCD/bin/dcd-client",
    "d.dcdServerPath": "/home/muhammad/.local/share/code-d/bin/DCD/bin/dcd-server",
    "[d]": {
    },
    "d.enableStaticLinting": false

 ---------------------
Server: 2018-04-10T15:28:22.672:first.d:visit:418 Could not resolve location of module 'jynx/crypto'

Server: 2018-04-10T15:28:22.672:first.d:visit:418 Could not resolve location of module 'jynx/datetime'

Server: 2018-04-10T15:28:22.672:first.d:visit:418 Could not resolve location of module 'jynx/string'

Server: 2018-04-10T15:28:22.672:first.d:visit:418 Could not resolve location of module 'vibe/core/net'

**Comment by WebFreak001** [comment]
It seems that config might not been known at startup, I fixed it now that it definitely must know the config before attempting to start anything. Can you try reloading the window to automatically fetch the newest version? Also pushed a new code-d version fixing seemingly random recompilations of an up-to-date serve-d

**Comment by mohamed-samir-mohamed** [comment]
yes it is now ignoring DUB, but there is still a problem, which is Dscanner is alwayes working although I disabled dubStaticLinting

**Comment by mohamed-samir-mohamed** [comment]
d.enableStaticLinting": false,
    "d.enableDMDImportTiming": false,
    "d.enableAutoComplete": true,
    "d.enableFormatting": false,
    "d.enableSDLLinting": false,

**Comment by mohamed-samir-mohamed** [comment]
actually it is not taking into account any setting I add, it just enables everything, Dscanner, sdl, dfmt, which is super slow in my project size, can you maybe have a look at this please :)

**Comment by WebFreak001** [comment]
uh did you update yet? It should be fixed now and I can't reproduce it with current master build of serve-d (set betaStream to true to automatically get master build)

**Comment by mohamed-samir-mohamed** [comment]
1.17.2, let me try betaStream

**Comment by mohamed-samir-mohamed** [comment]
dsymbol 0.2.9: building configuration "library"...
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(189,15): Error: no property 'symbol' for type 'const(Type2)'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(189,42): Error: no property 'symbol' for type 'const(Type2)'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(192,23): Error: no property 'symbol' for type 'const(Type2)'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(248,35): Error: no property 'identifierList' for type 'const(AliasDeclaration)'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(938,14): Error: no property 'symbol' for type 'const(Type2)'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(939,18): Error: no property 'symbol' for type 'const(Type2)'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/semantic.d(123,21): Error: no property 'symbol' for type 'dparse.ast.Type2'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/semantic.d(124,21): Error: no property 'symbol' for type 'dparse.ast.Type2'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/semantic.d(128,21): Error: no property 'symbol' for type 'dparse.ast.Type2'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/semantic.d(130,21): Error: no property 'symbol' for type 'dparse.ast.Type2'

I am using dmd v 2.76.1

**Comment by WebFreak001** [comment]
wtf? I did dub upgrade, dub build --force and can't reproduce this at all...

Can you try manually cloning serve-d and try building? Looks like some issue with dependencies :/

**Comment by mohamed-samir-mohamed** [comment]
trying

**Comment by mohamed-samir-mohamed** [comment]
I managed to build it after cleaning the dub cache,
rm -rf ~/.dub
but now I am getting this

![image](https://user-images.githubusercontent.com/1665565/38618532-3b85547e-3d9a-11e8-8718-196f870efc35.png)

**Comment by WebFreak001** [comment]
is the serve-d file marked as executable?

**Comment by mohamed-samir-mohamed** [comment]
I managed to fix it already, uninstall, remove code-d folder then installing again :+1:

**Comment by mohamed-samir-mohamed** [comment]
actually most of the functionality is working well except the d.projectImportPaths
I don't know what is wrong still with them, and one of my collegues is using OSX, and it is still ignoring the disable linting setting. :(

**Comment by mohamed-samir-mohamed** [comment]
oh acually, I have still my user settings ignored and still the dscanner tries to lint every thing, which is super slow.

**Comment by WebFreak001** [comment]
hm dscanner isn't super slow though, are you sure it's dscanner and not dub? It should say in the problems panel in vscode

**Comment by mohamed-samir-mohamed** [comment]
with large files it is relatively slow, and watches for changes, yes I am sure,

![image](https://user-images.githubusercontent.com/1665565/38621405-1edd39e8-3da1-11e8-8aa0-f2faf01255f7.png)

**Comment by mohamed-samir-mohamed** [comment]
![image](https://user-images.githubusercontent.com/1665565/38621505-4dc7a63a-3da1-11e8-878d-419ef8bbf5e8.png)

**Comment by WebFreak001** [comment]
uh as you managed to get it working in #191 I suppose this can be closed
