### ISSUE TITLE
no completion on osx

### ISSUE THREAD

**Issue by Extrawurst** [Pure-D/code-d#29]
i think i might have missed something while setting up but i cannot seem to get completion to work:
<img width="1226" alt="screen shot 2016-02-10 at 17 19 35" src="https://cloud.githubusercontent.com/assets/776816/12953474/e9f4bc2e-d01a-11e5-9862-5d7e2d700185.png">

rest of the log seems as if everything is setup correctly though:

```
[Plugin Host] Initialized code-d
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88 [Plugin Host] dub is ready
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88 [Plugin Host] DScanner is ready
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88 [Plugin Host] Dfmt is ready
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88 [Plugin Host] DlangUI is ready
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88 [Plugin Host] Array[1]0: "/Users/stephan/Documents/_gh/dcdtest/source/"length: 1__proto__: Array[0]
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88 [Plugin Host] provideHover
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88 [Plugin Host] provideCompletionItems
```

**Comment by WebFreak001** [comment]
Do you have some dependency in dub.sdl? workspace-d crashes when you depend on something that hasn't downloaded yet. Also it doesn't add the import paths for phobos, you should change those in the user settings.

Thats very weird. Do all processes run while its open? At the bottom there should be 2 more buttons "application" and "debug" and the processes workspace-d and dcd-server should run

**Comment by WebFreak001** [comment]
Might have been this issue: https://github.com/Pure-D/code-d/issues/30

Try updating workspaced & code-d now

**Comment by Extrawurst** [comment]
I update workspace-d now and now i get `'~/bin/workspace-d' is not a valid executable. Please...` in visual studio code.
my user settings are:
```
{
    "editor.insertSpaces": "auto",
    
    "d.stdlibPath": [
		"/Library/D/dmd/src/druntime/import",
		"/Library/D/dmd/src/phobos"
	],
	
	"d.workspacedPath": "~/bin/workspace-d",
	"d.dscannerPath": "~/bin/dscanner",
	"d.dfmtPath": "~/bin/dfmt"
}
```

the log looks like:

```
[Plugin Host] Initialized code-d
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88 [Plugin Host] WorkspaceD ended with an error:
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88 [Plugin Host] Error: spawn ~/bin/workspace-d ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:442:9)
    at process._tickCallback (node.js:356:17)
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:87 '~/bin/workspace-d' is not a valid executable. Please check your user settings and make sure workspace-d is installed!
```

**Comment by WebFreak001** [comment]
try replacing it with /home/USER/bin/workspace-d, it does not expand tildes

**Comment by Extrawurst** [comment]
ok not using tildes makes it find workspace-d again, even though the error in the first screenshot stays exactly the same:

```
[Plugin Host] provideCompletionItems
workbench.main.js:110 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:68:23327
    at Object.h [as _notify] (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:26637)
    at Object.n.undefined.O.enter (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:29799)
    at n.undefined.t.Class.define._run (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:31625)
    at n.undefined.t.Class.define._completed (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:31066)
    at Object.h.handle (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:56:29131)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88:20404
    at ChildProcess.<anonymous> (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88:23041)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
```

also no i am not using any dependecies. just raw result of a `dub init foo`:

```
name "dcdtest"
description "A minimal D application."
copyright "Copyright © 2016, stephan"
authors "stephan"
```

**Comment by Extrawurst** [comment]
and yea no autocompletion ;)

**Comment by WebFreak001** [comment]
Not sure if it happens because osx rejects something there. Can you clone this repository and try debugging the extension? Simply click debug and start at the right. Error paths should be better then

**Comment by Extrawurst** [comment]
ok i used workspace-d-installer to create all current binaries and now the log shows more traffic but still no completion -.-
<img width="941" alt="screen shot 2016-02-11 at 19 36 10" src="https://cloud.githubusercontent.com/assets/776816/12986376/4121976a-d0f7-11e5-8017-bec9c910deb8.png">

**Comment by WebFreak001** [comment]
From the log it seems to work. Did you try pressing escape and then ctrl-space again a few times?

**Comment by Extrawurst** [comment]
nope

**Comment by WebFreak001** [comment]
hm the plugin definitely receives and parses the completion correctly. Also those logs are near the callback passing the arguments back so vscode should receive them correctly. It should be an issue with vscode, did you try closing the file at the top left and reopen it?

**Comment by Extrawurst** [comment]
this is the weirdest thing here... now after restarting the log again says nothing... like this morning. are u in the #d irc ?

**Comment by WebFreak001** [comment]
caused from https://github.com/Hackerpilot/DCD/issues/295

**Comment by WebFreak001** [comment]
is another dcd-server already running? https://github.com/Hackerpilot/DCD/issues/297

**Comment by bojan-misic** [comment]
From #32, this is the .gif of the scenario:

![vscode](https://cloud.githubusercontent.com/assets/5645089/13438550/c88cf75c-dfe9-11e5-9f02-b2ffba24df2d.gif)

Basically, **"Loading..."** hangs indefinitely even when symbols are received from dcd-server. Sometimes, though, I get the box shown, but literally after 1 minute or more.

I'm available for any help I can provide, maybe IRC?

**Comment by joaomoreno** [comment]
Hi guys, Code developer here. I just deep in this with @alexandrudima and @bpasero, both devs in the Code team as well. We're closing the issue on our side, since we nailed it to happen between workspace-d and the processes it manages.

Here's what's happening: your extension seems to resolve **any** language service request **only** once a second request comes along. The extension is always *off by one*. This explains why Intellisense doesn't work when ran consecutively: the first request gets resolved when we are already expecting the second one. A quick proof of this: trigger Intellisense and, while it says `Loading...`, hover over an identifier in the file. This will send another request to the extension (hover provider), thus completing the first one (completion items).

![bug](https://cloud.githubusercontent.com/assets/22350/13468375/9b6c7aae-e0a2-11e5-9f92-6b9e11d87fc9.gif)

We verified this by adding some code to append to a log file in [source/app.d#24](https://github.com/Pure-D/workspace-d/blob/master/source/app.d#L24). If you do that you'll quickly realise that workspace-d itself doesn't write to stdout until the next request comes along.

There is indeed some stream buffering happening between workspace-d and the processes it spawns, and it seems to happen only on OS X. We stopped investigating there. :+1: 

Good luck!

**Comment by WebFreak001** [comment]
Oh thank you for finding the reason. Im gonna fix it with Extrawurst on the IRC

**Comment by Extrawurst** [comment]
@WebFreak001 unfortunately your patched js file did not change a thing. but what i found out now is that when the "loading" tooltip appears i can click on it with the mouse and THEN it shows the content XD - WTF

**Comment by WebFreak001** [comment]
Basically the issue is right here: http://dpaste.com/30BB343 but i have no idea how to fix it. Also can somebody on OSX try it out? I just pulled that code out and it works on linux but idk if that will be enough to reproduce the problem. So if somebody on OSX could try the code out, would be nice

**Comment by bojan-misic** [comment]
It runs for me on OSX. I see the line `DOESNT GET HERE ON OSX`.

**Comment by WebFreak001** [comment]
Hm so its more than just the dcd.d class. Its a combination of both the DCD and the caller. Interesting.

**Comment by WebFreak001** [comment]
I have just pushed some synchronization stuff to workspace-d ~master. If you want to compile workspace-d and try it in code-d, it might possibly work now. But im not sure as i can't test it myself because I dont have access to any OS X thing

**Comment by Extrawurst** [comment]
i just updated all binaries using workspace-d-installer and updated code-d and vscode and still the same behaviour :/

**Comment by h1kka** [comment]
I think i have the same problem.
Windows 7 x86.
![vscoded](https://cloud.githubusercontent.com/assets/6502466/13894689/e8e187ee-ed7b-11e5-9ee8-23f1235ffee8.jpg)
Loading never ends.

**Comment by WebFreak001** [comment]
@h1kka in your case workspace-d doesn't handle the request or code-d has problems sending/receiving it which is really strange. In the other cases workspace-d and code-d work but there are buffering issues

**Comment by claudiug** [comment]
any news with this?

on osx is not usable :)

**Comment by WebFreak001** [comment]
No idea. Did you try compiling workspace-d with LDC instead?

**Comment by claudiug** [comment]
nop, I just use dcd and workspace-d install.d
anyway, neither on irc, not a lot of people are using vscode with mac osx. On sublime is working properly. 👍 )

Is normal to make it work on osx I need to edit to files in extension itself?
`workspace-d.ts and package.json`?

**Comment by WebFreak001** [comment]
No I think this issue is on the workspace-d site and has something to do with the OS buffering

**Comment by claudiug** [comment]
Do you think is gonna be solved, should I wait or just use sublime or d-mono? :)

**Comment by WebFreak001** [comment]
No idea when this will be solved, use some other plugin on OSX

**Comment by claudiug** [comment]
ok. thx

**Comment by claudiug** [comment]
<img width="1280" alt="screen shot 2016-06-04 at 11 03 22 am" src="https://cloud.githubusercontent.com/assets/969118/15798752/09ec7566-2a44-11e6-9da7-5d968c10ac20.png">

**Comment by claudiug** [comment]
given the image above. the autocomplete sometimes works, but is very slow :)

`"d.stdlibPath": [
        "/Library/D/dmd/src/druntime/import",
        "/Library/D/dmd/src/phobos"
    ],

    "d.workspacedPath": "/usr/local/bin/workspace-d",
    "d.dscannerPath": "/usr/local/bin/dscanner",
    "d.dfmtPath": "/usr/local/bin/dfmt"
`
those are dlang settings

**Comment by WebFreak001** [comment]
Well the issue is that every command is one command behind. The commands do work but always lag

**Comment by claudiug** [comment]
I wish I could her here. Have no idea where to look

**Comment by Extrawurst** [comment]
looks like this is fixed now, even though loading resolves takes ages sometimes

**Comment by Andrepuel** [comment]
Hello. I've been able to track the issue. I've filed a bug report to the Phobos standard library:

https://issues.dlang.org/show_bug.cgi?id=16686

The issue happens in the workspace-d process, basically, the main thread is acquired a lock the stdin to perform a read, and the getFD function invoked by spawnProcess is trying to lock stdin and this blocks the thread until the read in the main thread is fulfilled.

I've done a simple workaround where I replace the global stdin for a File pointing to /dev/null. I am going to open a pull request in the workspace-d project and the community might judge if the solution is acceptable. Follows the diff:

    diff --git a/source/app.d b/source/app.d
    index acf95cb..d5757e6 100644
    --- a/source/app.d
    +++ b/source/app.d
    @@ -11,7 +11,17 @@ import std.exception;
     import std.bitmanip;
     import std.process;
     import std.traits;
    -import std.stdio;
    +version (OSX) {
    +       import std.stdio : stdout, stderr, File;
    +       static import std.stdio;
    +       File stdin;
    +       static this() {
    +               stdin = std.stdio.stdin;
    +               std.stdio.stdin = File("/dev/null", "r");
    +       }
    +} else {
    +       import std.stdio;
    +}
     import std.json;
     import std.meta;
     import std.conv;

**Comment by Andrepuel** [comment]
https://github.com/Pure-D/workspace-d/pull/53

**Comment by WebFreak001** [comment]
Neat, thanks! Anyone on OSX wanna try it out now again with ~master workspace-d? Should be fixed now then.

**Comment by WebFreak001** [comment]
Confirmed fixed using workspace-d ~master by @alphaKAI

**Comment by zhuge-ei** [comment]
it's been two long years and still having this "loading" problem 

Cmon,it's a very simple looking bug that should have been fixed by now :-1: :-1:

**Comment by WebFreak001** [comment]
@zhuge-ei make a new issue with error logs, you have 99% surely a different issue than this

**Comment by WebFreak001** [comment]
I locked the issue because the code base has changed way too much since this issue was opened. Any issues now will not have anything to do with the issue that was experienced 2 years ago. It just only says `Loading...` from vscode side because _some component hangs or crashed_ when auto completing or hovering. As that can be a very wide spectrum of reasons I think it's better to [create a new issue](https://github.com/Pure-D/code-d/issues/new) instead! Please make sure you include the logs as described in the template text when creating a new issue.

If you don't want to create a new issue you can still join us on discord to get direct support and help from me and others https://discord.gg/Bstj9bx
